---
version: '3'

volumes:
  mosquitto-data: {}

services:
  informa:
    image: ghcr.io/mafrosis/informa:dev
    restart: unless-stopped
    build:
      context: .
    environment:
      - DEBUG
      - MQTT_BROKER
      - MAILGUN_KEY
    volumes:
      - ./plugins.yaml:/src/plugins.yaml:ro
      - ./templates:/src/templates:ro
      - ./config:/src/config:ro

  test:
    image: ghcr.io/mafrosis/informa:test
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - MYPYPATH=/mypy-stubs
    volumes:
      - ./informa:/src/informa
    depends_on:
      - informa

  mqtt:
    image: eclipse-mosquitto:2.0.11
    restart: always
    ports:
      - 1883:1883
    volumes:
      - mosquitto-data:/mosquitto/data
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
