---
version: '3'

volumes:
  informa-data: {}

services:
  informa:
    image: ghcr.io/mafrosis/informa:dev
    restart: unless-stopped
    build:
      context: .
    environment:
      - DEBUG
      - MAILGUN_KEY
      - TZ=Australia/Melbourne
    ports:
      - 3002:3002
    extra_hosts:
      locke: 192.168.1.198
    volumes:
      - ./plugins.yaml:/src/plugins.yaml:ro
      - ./templates:/src/templates:ro
      - ./config:/src/config:ro
      - ./gcp_oauth_secret.json:/src/gcp_oauth_secret.json:ro
      - informa-data:/src/state

  test:
    image: ghcr.io/mafrosis/informa:test
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - MYPYPATH=/mypy-stubs
    volumes:
      - ./informa:/src/informa
    depends_on:
      - informa
