---
volumes:
  informa-data: {}

services:
  informa:
    image: ghcr.io/mafrosis/informa:dev
    restart: unless-stopped
    command: start --host 0.0.0.0 --port 3000
    build:
      context: .
    environment:
      - DEBUG
      - MAILGUN_KEY
      - MP3HOME=/music
      - TZ=Australia/Melbourne
    ports:
      - 3000:3000
      - 3002:3002
    volumes:
      - ./plugins.yaml:/src/plugins.yaml:ro
      - ./templates:/src/templates:ro
      - ./config:/src/config:ro
      - ./gcp_oauth_secret.json:/src/gcp_oauth_secret.json:ro
      - /home/mafro/music:/music:ro
      - informa-data:/src/state

  test:
    image: ghcr.io/mafrosis/informa:test
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - MYPYPATH=/mypy-stubs
    volumes:
      - ./informa:/src/informa
    depends_on:
      - informa
