---
volumes:
  informa-data: {}

services:
  informa:
    image: ghcr.io/mafrosis/informa:dev
    restart: unless-stopped
    command: start --host 0.0.0.0 --port 3000
    build:
      context: .
    environment:
      - DEBUG
      - MAILGUN_KEY
      - MP3HOME=/music
      - GSUITE_OAUTH_CREDS=/src/gcp_oauth_secret.json
      - TZ=Australia/Melbourne
    ports:
      - 3000:3000
      - 3002:3002
    extra_hosts:
      locke: 192.168.1.198
    volumes:
      - ./plugins.yaml:/src/plugins.yaml:ro
      - ./templates:/src/templates:ro
      - ./config:/src/config:ro
      - ./mafro-oauth-abad62e69e8d.json:/src/gcp_oauth_secret.json:ro
      - /home/mafro/music:/music:ro
      - informa-data:/src/state
