version: '2'

volumes:
  redis-data: {}

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - informa
      - celery

  memcache:
    image: memcached:alpine
    ports:
      - 11211:11211

  redis:
    image: redis:3.2.6-alpine
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

  celery:
    image: mafrosis/informa:dev
    command: celery worker -A manage.celery --workdir=/srv/app --purge
    environment:
      - C_FORCE_ROOT=1
    volumes:
      - ./:/srv/app
      - /srv/app/.git
    depends_on:
      - redis

  celerybeat:
    image: mafrosis/informa:dev
    command: celery beat -A manage.celery
    volumes:
      - ./:/srv/app
      - /srv/app/.git
    depends_on:
      - redis
      - celery

  informa:
    image: mafrosis/informa:dev
    command: ./manage.py runserver --host 0.0.0.0 --port 8003
    build:
      dockerfile: config/Dockerfile
      context: .
      args:
        - BUILD_TAG=${BUILD_TAG}
    volumes:
      - ./:/srv/app
      - /srv/app/.git
    ports:
      - 8003:8003
    depends_on:
      - celery
