version: '2'

volumes:
  redis-data: {}

services:
  redis:
    image: redis:3.2.6-alpine
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

  celery:
    image: mafrosis/informa:dev
    command: make celery
    volumes:
      - ./:/srv/app
      - /srv/app/.git
      - /etc/localtime:/etc/localtime
      - /home/mafro/watch:/watch
    depends_on:
      - redis

  celerybeat:
    image: mafrosis/informa:dev
    command: make celerybeat
    volumes:
      - ./:/srv/app
      - /srv/app/.git
      - /etc/localtime:/etc/localtime
    depends_on:
      - redis
      - celery

  flask:
    image: mafrosis/informa:dev
    command: make flask
    build:
      dockerfile: config/Dockerfile
      context: .
      args:
        - BUILD_TAG=dev
    volumes:
      - ./:/srv/app
      - /srv/app/.git
      - /etc/localtime:/etc/localtime
      - /home/mafro/watch:/watch
    ports:
      - 8003:8003
    depends_on:
      - celery
